#+TITLE: How do humans compare to other animals regarding AGT?
- sources :: cite:sep-game-theory
- tags :: [[file:20200519191955-how_cognitive_complexity_impacts_the_applicability_of_gt.org][How cognitive complexity impacts the applicability of gt?]]



* q :fc:
:PROPERTIES:
:FC_CREATED: 2020-05-21T00:42:59Z
:FC_TYPE:  normal
:ID:       c180a984-9827-4b2d-aae0-eebeca213a48
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |   0 |        0 | 2020-05-21T00:42:59Z |
:END:

** Back
 Good for simple animals. Not-eusocial animals is not so good. Why?
  #+begin_quote
 Besides greater cognitive complexity
  the stabilization of internal control dynamics is partly located outside the
  individuals, at the level of group dynamics.
  #+end_quote

  Humans are the hardest we know about. Because :
  #+begin_quote
Humans socially controlled to an extreme degree by comparison with most other
  non-eusocial species. At the same time, their great cognitive plasticity
  allows them to vary significantly between cultures. People are thus the least
  straightforward economic agents among all organisms.
  #+end_quote

  So, Ross' theory is that the applicability of game theory is dependent on cognitive complexity on one side and external systemic control on the other. Humans are arguably complex at both, which explains why they are so hard to model.
