#+TITLE: My Fleeting Ideas
- tags :: [[file:20200628152829-my_weltanschauung.org][My Weltanschauung]]


Here are fleeting notes that ought to be better developed.


* Democratic advantage and ergodicity


  Many political theorists make dynamic arguments - about properties in time series. The insight is that the argument for democracy makes arguments about ensemble AND time averages. This is in robert dahl, mcgann even tocqueville. This should be formalized and connected with wanderley guilherme dos santos discussion about democratic transitions.

* Empirical dialectics and negativity


tenho um plano dormente de em contraponto a elster tentar make sense da epistemologia marxista.n uma defesa,mas atualizar e manter os insights (a la lawvere).obviamente precisaria expurgar o infalibilismo.quando se pensa uma dialetica falibilista o negativo ganha mais importancia


quando falo epistemologica tou pensando como o sistema "logico" vai levar a entender categorias e de quebra a pesquisa empirica
acho que o insight de marx na inversao dele em hegel é exatamente essa. dialetica pode ser invertida exatamente para nos ajudar a ver os buracos de conhecimento que enquanto em hegel sao resolvidos com mais abstracao em marx leva a investigacao da realidade concreta, mas ai ele tava imerso numa epoca em que a visao de conhecimento n era falibilista o bastante. acho que esse é o grande problema do sistema do ponto de vista cientifico

essa nocao de buracos acho tooopo

pq em prog mesmo vc deixa "buracos" no codigo e o sistema infere pra vc a partir de dicas. acho que tem um angu metodologico aqui

mas a partir o momento em que o falibilismo entre em cena a relacao entre categorias tem que ser mediada pela incerteza das proposicoes. intuitivamente isso leva a negatividade de adorno. enfim inutilidade da porra


no fim eu tenho a visao que da pra unificar a pratica cientifica por meio de uma triade de fontes: analiticos <-> pragmatistas <-> hegelianos materialistas ; como bom pos marxista acho que cada um é unilateral por um lado mas contribui por outro e que da pra unificar num sistema so

* From laws to algorithms
  From laws to principles to mechanisms to models to algorithms.

  My aim is to frame different ways of doing positive social theory. I'll show
  that those concepts suggest pretty different ways of representing and
  explaining the world.

  In this end this is part of a bigger project in algorithmic political theory.

  A good reference is:
- cite:Knuth1974art
- pearl works
- [[https://an1lam.github.io/post/2020-05-15-ci-course-review/][Stephen Malina - Course Review - Causal Inference]]
- The social software view
- the literature on modeling vs laws (weisberg, clarke and primo)

  
* Universalism and Social Choice


  To take balibar view of universalism as a site of conflict and connect with
  both social choice (universal domain) and the theory of majorities as
  coalitions of minorities. Any "universal" aggregation is leaving something
  out, and from a reflective point of view is open to criticism.

* Social choice results as artifacts
- source :: cite:sep-voting-methods

  Pacuit makes the same question as I did years ago:
  #+begin_quote
  The main question is whether the voting paradoxes are simply features of the
  formal framework used to represent an election scenario or formalizations of
  real-life phenomena. This raises a number of subtle issues about the scope of
  mathematical modeling in the social sciences,
  #+end_quote

  This is directly related to the probability of any of the paradoxes
  (behavioral social choice) and to showing that they indeed occurred in an
  empirical setting (riker vs makie).

* What are the 2 normative views of SCFs?
- source :: cite:sep-voting-methods

  One can justify and analyze social choice using a *procedural* (the right way)
  view or an *"epistemic"* (consequentialist).

  The most general article in the epistemic program is cite:Pivato_2012 .
  Conitzer also has some works on this approach (seeing SCFs as mles;
  cite:Conitzer_2013). This epistemic view is directly relevant to a project idea of using social choice to study ensembles.


* Social Choice and Central Authority




One implicit assumption in the Social Choice literature is that the work will be consumed by some sort of central authority, benevolent dictator. That is why cite:sep-voting-methods considers that the central question of social choice is the following:

#+begin_quote
Given a group of people faced with some decision, how should a central authority combine the individual opinions so as to best reflect the “overall group opinion”?
#+end_quote

This is a top down and statist perspective on group-decision making. One thing it ignores is the problem of choosing how to choose. That is something discussed by cite:Buchanan_1960 and its descendants. Group decision-making goes well beyond such liberal technocrat view and how to  incorporate social choice theory into such a bottom-up perspective.

For an almost anarchist approach to political economy see aligica and similars :
- cite:johnson19_remar_paul_dragos_aligic_public
- cite:allen18_crypt_its_instit_possib


* levels, abm and markov coarse graining
- use baez , isquierdo, dedeo and catlab to think about this project
- see more and organize that 

* evo aumann program
use information geometry with evo gt in combination with epistemic game theory


[[https://johncarlosbaez.wordpress.com/2012/06/07/information-geometry-part-11/][Information Geometry (Part 11) | Azimuth]]
[[https://johncarlosbaez.wordpress.com/2012/06/24/information-geometry-part-12/][Information Geometry (Part 12) | Azimuth]]
The 14 starts an interesting discussion about nonequilibrium steady states which connect with both page and papadimitrious works



* petri nets and bayesian networks
[[https://www.sciencedirect.com/science/article/pii/S0304397519304694][Bayesian network semantics for Petri nets - ScienceDirect]]
Petri nets are used in the julia ecosystem as a general template for both abm's and differential equations. I'm interested how they can be used to connect the literature on simulation with the empirical literature on causal inference. This would be a huge methodological contribution.

* Social computational trinitarianism

Epstein in generative social science argues that code is math to defend the usage of abms. My interest is to go further and see how to actually connect logic with math with computation. Particularly, how to turn "informal theories" into logic into math into computation and how this may be connected with empirical research.

[[https://www.frontiersin.org/articles/10.3389/fevo.2019.00402/full][Frontiers | Artificial Intelligence for Ecological and Evolutionary Synthesis...]] is something that might help here 
