#+title: Long summary of taking smart notes

#+OPTIONS: toc:nil
#+OPTIONS: date:nil

# - refs :: cite:ahrens2017take
# - tags :: [[file:20200525200536-on_my_workflow.org][On my workflow]], [[file:20200714124711-summary_of_taking_smart_notes.org][Summary of taking smart notes]],

* Introduction

*(gist)*

He defends the fundamental importance of organization and methods in a
study/research routine for a successful career in academia. We have to think
about the whole *organization* of writing, not only the "final" moment in which we
write an essay, article or book. Writing does not follow research, it is the
*medium* of research, and "successful writing lies in the preparation".


*(main concepts)*
Notes;  environment; methodology; tasks


*(specific arguments)*

We have to pay special attention to the organization of research. Academia is not about IQ, but about self-discipline, or more precisely about using a system (given willpower depletion).

Psychological issues happen, however anxiety is intensified by a lack of structure and thinking that we have to start writing with a blank piece of paper.

  #+begin_quote
  Getting something that is already written into another written piece is
  incomparably easier than assembling everything in your mind and then trying
  to retrieve it from there.
  #+end_quote

Self-control is about the environment. Define meaningful/interesting/precise
tasks. 
  #+begin_quote
Having a meaningful and well-defined task beats willpower every time.
  #+end_quote



* Everything You Need to Know

*(gist)*

He present Luhmann's method and argue that it is simple, adaptive and ultimately
useful, maybe as useful as say Ford's method in industry, or GTD in business.
*Studying/research methods should be simple, open-ended and adaptive* and
Luhmann's method is such a system.


*(main concepts)*
- structure
- flow
  #+begin_quote
the state in which you get so completely immersed in your work that you lose track of time and can just keep on going as the work becomes effortless
  #+end_quote
- workflow
- work in vs plan about (expert vs planner)
- slipbox


*(specific arguments)*
Having a methodology relieves the burden of routine, research and so on. Things don't need to be held your head. *Break down tasks into small and clearly separated tasks.*
*Flow* does not happen by chance, it can be engineered. That is why we call it *workflow*. One should have a structure to work *in* not plans *about* stuff.
  #+begin_quote
Having a clear structure to work in is completely different from making
plans about something. If you make a plan, you impose a structure on
yourself; it makes you inflexible. To keep going according to plan, you have
to push yourself and employ willpower.
  #+end_quote

The best way to deal with complexity is by KISS. Routine is about simple, repeatable and seamlessly integrated tasks. Tools and tasks must fit together.

Micromanagement is bad for open-ended tasks (such as research) (once again the difference between plan and tasks). Notes are only valuable in context, and this is not necessarily the context they are taken from. The structure should allow small and constant adjustments:
  #+begin_quote
If we work in an
environment that is flexible enough to accommodate our work rhythm, we
don’t need to struggle with resistance. Studies on highly successful people
have proven again and again that success is not the result of strong willpower
and the ability to overcome resistance, but rather the result of smart working
environments that avoid resistance in the first place
  #+end_quote

Luhmann had two slip-boxes: a bibliographical one and the main one.  His workflow was organized in 3 steps:
  1. Write bibliographical notes and *shortly after*, by taking a look at brief and reference notes, think about their relevance for his work/ideas
  2. and write them in different notes: ideas, thoughts, comments and so on.
  3. Whenever one adds those permanent notes look for relevant notes and link them.
The trick of Luhmann workflow is that it is not organized by topic, but by indexation, by linking. The last element of his workflow are *index notes*, they are entry points to a theme and may contain a collection of links.

* Everything you need to do

*(gist)*

He intends to demonstrate how the zettelkasten workflow leads to papers which
emerge from your routine. One only has to follow the 8 steps.

*(main concepts)*

fleeting notes; literature notes; index notes; permanent notes; inbox ; reference system; desktop notes


*(specific arguments)*

- Writing a paper is an  8 steps process
  1) Make fleeting notes
     - reminders of what is in your head
     - put them into one place: *inbox*
  2) Make literature notes
     - notes about contents
     - things that don't want to forget or that might use in your own writing
     - try to use own words. Quotes should be only used if you really understand what they mean and their usage is akin to the one in articles
     - keep them with their bibliographic details, one must have a *reference system*
  3) Make permanent notes
     - Go through notes in step 1 and 2 and see how they relate with your ideas, projects, interests.
     - The idea is *not* to collect, but to develop ideas/arguments
     - Here are we ask ourselves the sonke questions
     - while in the literature notes we are writing to ourselves, here write as if for someone else.
     - *throw away fleeting notes* and "archive" literature notes in the reference system.
  4) Add your permanent notes to the slip-box
     - Link it to other notes (maybe an index)
  5) Develop topics/questions/research projects from within the system
     - *Always take the path that promises the most insight*
     - Don't get stuck in an idea if another gains momentum
  6) Decide on a topic to write about
     - This is *based on what you have* !
     - Put your notes into a *desktop*: an ordered index note for a specific project
  7) Translate notes into a manuscript
  8) Edit and proofread the manuscript

* 3&4

*(gist)*

He reminds the reader that *zettel requires a routine of connection and note
processing*. One has to continuously process and connect notes, lest one creates
a graveyard for thoughts instead of a living tool for thought.

*(main concepts)*

- thoughts graveyard

*(specific arguments)*

We have to be careful to not turn the slipbox into an archive for notes or a graveyard for thoughts!
Therefore fleeting notes should be processed ideally within a day.


* Writing Is the Only Thing That Matters

*(gist)*

He argues that writing is the goal and our routine must pay heed to that.
*Sharing, publicizing, is the final goal of any study.* Therefore, we must always
write, and streamline our routine with publicizing our ideas and findings as the
telos.

*(main concepts)*

tangible purpose (writing)

*(specific arguments)*


#+begin_quote
the professor is not there for the student and the student not for the
professor. *Both are only there for the truth. And truth is always a public
matter*. Everything within the university aims at some kind of publication.
#+end_quote

If all that matters is truth, and truth is public, therefore ought to be published; and studying is researching, then studying is all about publishing. *One should work as if nothing else counts than writing.*

Studying is not preparation for research, it is research. You gain insight, you test things out, and then you share (publish).
  #+begin_quote
An idea kept private is as good as one you never had. And a fact no one can reproduce is no fact at all.
  #+end_quote

This focus on writing gives you a *tangible purpose* when engaging in activities (this leads me back to tasks). I might adapt that by creating *beginning questions*: *Why am I reading this? Where is this might be useful? Which project or idea that I already have will benefit from this and how?*
This focus on writing also leads to focus on learning things that allow you develop *specific* ideas and projects.
Also, in terms of writing notes, to *only write things that you think help with some idea/project or is giving you new insights*. Studying is not about archiving!




* Simplicity is paramount

*(gist)*

He reminds us that *there are different kinds of things we write. Not all of
them should go into the slip-box*. It is important to distinguish between those
types of notes so that our system evolves:
- Fleeting notes go into the inbox
- Literature notes go into the reference system
- Project notes (todos, drafts, project related literature, reminders) go into
  project specific repositories
- Main notes go into the slip-box.

*(main concepts)*

- literature x project x permanent notes
- fleeting notes pile
- project notes


*(specific arguments)*

All the studying process should be streamlined with the goal of publishing your
findings. When linking a note the guiding rule is :

#+begin_quote
 In which context will I want to stumble upon it again?
#+end_quote

Distinguishing between kinds of notes is paramount for achieving a critical mass
of ideas. He talks about three kinds of notes. First, *fleeting notes*. They are thrown away in a few days. Underlining or writing comments on a text can be seen as fleeting notes and are only useful if you review, turn into proper notes, and throw away. Second, *permanent notes*.
They either live in the reference system or in the slip-box
and contain all the necessary information in themselves. Literature notes can be brief, while main notes are written with more care. Third,  *project notes*. These live inside project-specific folders and can be discarded,archived after it is finished. But what the heck are project notes?

  #+begin_quote
   - comments in the manuscript
   - collections of project-related literature
   - outlines
   - snippets of drafts
   - reminders
   - to-do lists
   - and of course the draft itself.
  #+end_quote

Why the distinction? *One should not collect ideas and treat every idea as a permanent note.* This will crowd the system.
On the one hand, you should *not* only take notes related to specific *projects*, since you are developing a  permanent reservoir of ideas. On the other hand, One also should not collect fleeting notes!! This will lead to *piles* of fleeting notes. That is why they are temporary and should be turned into permanent notes. Before storing literature notes, in the end of the day, try to think about their relevance for your ideas/projects and write about  it in permanent notes. Every *permanent note* should be elaborated enough to have the potential to *become part of or inspire a written piece*. 




* Nobody Ever Starts From Scratch

*(gist)*

He defends an iterative approach to research. We start from the slipbox and NOT
at a blank page. Since projects are started from within the slipbox, we keep
studying and then we stumble upon them.

*(main concepts)*

pool of externalized thoughts;  slip-box-storming

*(specific arguments)*

Starting with the topic is not grounded in reality. To ask a question one has to have thought about the topic. And reading about topics is also grounded on previous preoccupations. Actually one should start with your preoccupations, read about the topics, take notes and grow a *pool of externalized thoughts*. Starting a research project, should, therefore, begin with a slip-box storming instead of a brainstorm. 



* Let the Work Carry You Forward

*(gist)*

He argues that a good system empowers us, but to do so we must test ourselves.
If we push ourselves the work will propel us. In the beginning it will *feel the opposite*, but having a feedback system will have lasting effects.

*(main concepts)*

learning feedback loops

*(specific arguments)*

One should look for a workflow that propels us, instead of sucking our energy and requiring more and more work. Work itself should be motivating. External rewards are not enough. This is useful even for sports.

Seeking feedback is important for growth, and as such one has to *incorporate feedback loops in the learning system* (only when trying to publish is bad, too little). This means not only asking for other people feedback, but also to test yourself all the time. Push yourself. Use active learning tricks. Try to train differentiating what should be written and what should not. Writing permanent notes is also a way of testing ourselves
  #+begin_quote
Expressing our own thoughts in writing makes us realise if we really thought them through.
  #+end_quote


* Separate and Interlocking Tasks

*(gist)*

He defends the importance of "uni-tasking" and tasks blocks. *We must develop a
workflow which has concrete tasks which we give our undivided attention*, but
there are different kinds of tasks in terms of attention, memory and motivation.
Being concrete, instead of amorphous, and putting "similar" tasks in blocks
let us be productive instead of depleted by the process.

*(main concepts)*

mere exposure effect; proofreading; outlining; reading and writing tasks; amorphous vs focused tasks attention, short-term memory and motivation; ego depletion


*(specific arguments)*

Give each task undivided attention. That is, *do not multitask*. Even writing involves lots of different tasks. This means that *we should separate those tasks in blocks and do them one at a time*. For example organizing, editing, correcting and rewriting are different things and should be done one at a time. Writing code is different from documenting which is different from testing it.  Also, *remove all distractions*.

*Give each task the right kind of attention*  e.g. proofreading is very different from writing (smooth out patches, check for typos). This distance is necessary to see the text, *not our thoughts*. What we "mean" is different from what is given by the text. On the other hand,  we should not proofread WHILE writing. Those are two different kind of tasks. If we proofread while writing our writing will be painfully slowed down. Other example of different tasks in writing is that finding the right words is different from thinking about the structure of the text (outlining). The outline should be easily accessible while writing, but not done all the time.

Ok, but what are some subtasks in the category "writing"?
  - proofreading,
  - formulating,
  - outlining,
  - developing thoughts,
  - combining thoughts

Even reading can be split into reading tasks:  Skim vs scan. Most texts should be only skimmed. However, even texts we want a deeper understanding can be profitably skimmed so that we get what is its structure, its outline.

Successful creative endeavors require both a playful open mind and a narrow analytical frame Once again he goes against making plans. *Following rules strictly make you a performer, not a master or even an expert of an activity.*

Remembering is much easier if we understand things. And understanding is about making connections. Open tasks occupy our short term memory and therefore unfinished tasks distract us.  them down help us "forget" about them.
This all leads to *breaking down amorphous tasks into smaller tasks* that can be finished in one go.

Reduce the number of decisions you make. This will leave more ego space for
important decisions. *Taking breaks is also important (walking, nap, and so on).*


* Read for Understanding

*(gist)*
He defends that when reading a text we should have a conversation with it. For that end we ought to have a *latticework of mental models and methods* which allow us to
see the *gist* of the work, its background and all kinds of argumentative
patterns. *Academic work should not be read as a novel.*

*(main concepts)*

paper \(\leftarrow\)  draft (continuous text) \(\leftarrow\) series of notes \(\leftarrow\) slipbox ;  *lattice of mental models*; confirmation bias; relevant x irrelevant information; *the gist x supporting details* ; Patterns, frames, distinctions


*(specific arguments)*

Do not copy, but translate. When taking notes try to *have a dialogue* with the text. Always read thinking about possible connections to notes in the  slipbox.
The extension of literature notes depend on the complexity and importance of the text. It is something to expect that notes about new subjects are more extensive. What matters is that they *support the creation of main notes*.

We must have a *lattice of mental models* to identify and describe the main ideas quickly. What is most helpful in reading is to think about *the background* of the text. Theory, method, goal, and so on.

The main distinction for the slip-box is the one of *relevant or irrelevant information*
The main skill to make this distinction is to be able to *get the gist* vs what is supporting details. Look for *patterns, frames and  typical distinctions* Reframe, contest distinctions, point out limitations.

One idea *I* take from this is that we must create those models through the *reading questions*, which themselves are something we always work on. SQ3R may also help.

Do not be too selective with your notes. and be careful with *confirmation bias*. It is part of a good argument to be able to withstand counterarguments and criticism!!! Therefore, we have to pay *special* attention to dis-confirming evidence and counterarguments.

*Understanding the text, translating it and connecting it are different tasks*!!!!
  1. Read
  2. Turn into literature note while reading, translating to your own words
  3. Later turn those notes into new main notes connecting with our previous insights and preoccupations.

The only criterion of addition into the slipbox is whether it contributes to something OR it may lead to new insights related to your previous interests

*Do not focus too much on individual projects, but towards all possible connections.*

* Take smart notes

*(gist)*

He argues that we have to create triggering cues in our minds, and we do that in
the zettel method by connecting notes. Seeing what is *missing, comparing,
contrasting*, contextualizing are all methods of creating a web of ideas that
will allow us to understand and create.


*(main concepts)*
*external scaffolding; *triggering cues*; cramming; contrasting

*(specific arguments)*


What distinguishes successful students from less succesful is *thinking beyond the frames of the source*. Pick a text. Read it with *your questions in mind* and *relate it to other approaches* instead of adopting the question of the text and how if frames things. Try to think about what *is not* in the text!! *DO NOT* collect de-contextualized quotes from a text
Once again, look at the gist vs supporting information. See how the propositions in the text relate to the gist. Be critical, including of outlining of the text, but in terms of your area theories, methods, goals, and so on.

Writing is the only way to think systematically, else there will be loopholes,
contractions, mistakes, in our thoughts. *That is why we have to *think outside
our brain*. Thinking is not an internal process, but an external one. That is
real thinking requires *external scaffolding*. The most typical external
scaffolding is through writing.
  #+begin_quote
“Notes on paper, or on a computer screen [...] do not
make contemporary physics or other kinds of intellectual endeavour easier,
they make it possible” is one of the key takeaways in a contemporary
handbook of neuroscientists (Levy 2011, 290) Concluding the discussions in
this book, Levy writes: “In any case, no matter how internal processes are
implemented, insofar as thinkers are genuinely concerned with what enables
human beings to perform the spectacular intellectual feats exhibited in
science and other areas of systematic enquiry, as well as in the arts, they need
to understand the extent to which the mind is reliant upon external
scaffolding.” (Ibid.)
  #+end_quote

Learning is about constructing *triggering cues* and not about storing information. The information ought to be connected to *meaningful contexts*.

*Elaboration* is a two step process : first you have to think about the piece of information as much as needed for writing about it, second, you think about the meaning of it for other things, ideas, contexts.

If you focus your time on *understanding* on finding justification, reasons, distinctions, connections it will be much easier to remember than cramming. Connecting is also about *comparing* and *contrasting*.

Typical literature notes questions:
  #+begin_quote
 "Is this convincing? What methods do they use? Which of the references are familiar?"
  #+end_quote

Typical main notes questions:
   #+begin_quote
*What does this all mean for my own
research and the questions I think about in my slip-box?* This is just another
way of asking: *Why did the aspects I wrote down catch my interest?*
#+end_quote



* Develop Ideas

*(gist)*

He argues that we should not focus on creating structure on the get go, rather
to elaborate on ideas. We should not only try to make "connections", but create
oppositions, *play, tinker, tweak and re-specify* what we read. Only through
*intense elaboration* is that we create something new.

*(main concepts)*

index; entry points; overview notes; note-to-note links x
 index-to-overview-to-notes links.; oppositions as idea creator; feature
 positive effect; *latticework of models and methods*;elaboration + spacing +
 variation + contextual interference + retrieval; play, tinkering, tweaking;
 re-specification;details x gist x missing;One idea per note = 1 page notes  ;restrictions as freedom


*(specific arguments)*

Overviews are not necessary. It is preposterous to have an overview of our thinking if we are still developing it
Indexes should not be exhaustive. Actually, they should have only *entry points to topics*. The previously established connections between the notes will do the rest.
We can have a temporary *overview of a topic* inside a note. And then link those "topic overviews" as entries in our index. AND THAT'S IT.
  #+begin_quote
The consideration of how to
structure a topic, therefore, belongs on notes as well – and not on a meta-
hierarchical level. We can provide ourselves with a (temporarily valid)
overview over a topic or subtopic just by making another note. If we then link
from the index to such a note, we have a good entry point. If the overview on
this note ceases to correctly represent the state of a cluster or topic, or we
decide it should be structured differently, we can write a new note with a
better structure and update the respective link from the index.
  #+end_quote

The question we should ask ourselves when tagging something is:
  #+begin_quote
In which circumstances will I want to stumble upon this note, even if I forget about it?
  #+end_quote

*Overview notes* are entry points to a subject. They will be listed in the index and in them are links to other notes on the topic *with a short description* (a short sentence). Don't go overboard. Those notes shouldn't have more than 25 (the luhmann maximum).

If you believe your overview notes are not adequate do not delete them. Add a new note, comment on the one before, and then specify the new structure of the topic. Most of the time, however, we will be making note-to-note links, instead of index-to-overview-to-notes links. Whenever we are going to add an idea to the slipbox we should ask ourselves, or imagine that the slipbox is asking us:

  #+begin_quote
  What is the reference? How does that connect to the facts and the ideas you already have?
  #+end_quote

Constructing oppositions is a great way of generating new ideas. Aufhenbung as well. Long preparation, tweaking, and getting real  good with the tools/device we work with is necessary for innovation.  Paradigm shift might be more about iterated steps towards the right direction than about big innovative stuff; Comparing, contrasting, connecting is *not enough*, we have to *play, tweak, tinker* with ideas.
  #+begin_quote
without intense elaboration on what we already know, we
would have trouble seeing its limitations, what is missing or possibly wrong.
  #+end_quote


Have a *theoretical-methodological toolbox*. Not a thorough theoretical understanding, but a flexible collection of many applicable models that might help you connect, contrast and understand things.

  #+begin_quote
A truly wise person is not someone who knows everything, but someone who is able to make sense of things by drawing from an extended resource of interpretation schemes
  #+end_quote

Learning should not be seen as accumulation of knowledge, but as building up a *latticework of models and methods*.
  #+begin_quote

We learn something not only when we connect it to prior knowledge and try
to understand its broader implications *(elaboration)*, but also when we try to retrieve it at different times *(spacing)* in different contexts *(variation)*, ideally
with the help of chance *(contextual interference)* and with a deliberate effort
*(retrieval)*.
  #+end_quote



- I *LOVE* this quote:
  #+begin_quote
Even very personal, intimate experiences, like encounters with art, require
abstraction. If the story of Romeo and Juliet touches us, it is certainly not
because we are all members of one of two feuding families in Verona. We
abstract from time and place, from the particular circumstances until we can
meet the protagonists of this story on a general level where our own
emotional life can resonate with what we see on stage. The tendency to
juxtapose abstraction with being worldly or to associate it with
intellectualism and juxtapose it with being solution-orientated is very misleading indeed.
  #+end_quote

Seeing *what is missing* is as important as seeing beyond details (*gist*).The typical strategy to solve problems is to redefine them as something that we have some tool to solve;
Following Feynmann, on the other hand it is important to keep unsolved problems in check as we learn new tricks.

Take simplicity seriously (*KISS*). Keeping your notes short is important as a way
of focusing on the *gist*.  *ONE IDEA PER MAIN NOTE*. If the note is short, precise and about one thing it can be freely recombined later. That is, *one page per main note!!!!* Literature notes should be stored as: "on page x it says y". Those restrictions liberate you.



* Share Your Insight

*(gist)*
Writing should become a *ritual*. We should look into our slip-box for ideas and
choose the ones which are interesting, relevant, doable, but not too easy. Those
*projects should be meaningful, speak to our personal goals,* otherwise we will
lose motivation.

*(main concepts)*

- overconfidence bias
- rituals
- kill your darlings


*(specifc arguments)*

Brainstorming leads to positive feature effect: you remember stuff which you've seen recently. Main notes are those aspects of a text we consider relevant to development of our ideas and our longer-term thinking.Most questions are not suitable to become an article, thesis, book. They might be too broad, too narrow, impossible to acquire the required knowledge, and so on. Good questions are: not easy, not impossible, and relevant (according to some criteria).

The following quote speaks a lot to my experience:
  #+begin_quote
When even highly intelligent students fail in their
studies, it’s most often because they cease to see the meaning in what they
were supposed to learn (cf. Balduf 2009), are unable to make a connection to
their personal goals (Glynn et al. 2009) or lack the ability to control their own
studies autonomously and on their own terms
  #+end_quote

Three pillars:
- Do something which has meaning
- Do something which connects with my personal goals
- Do something in my own terms

This is a maximalist criteria, obviously. Maybe do something which has meaning and is aligned with my personal goals. Meaning here is the main challenge.

*This is gold*: we should
#+begin_quote
[...] accompany *every step* of our work with the question “What is interesting about this?” and *everything we read* with the question, “What is so
relevant about this that it is worth noting down?”.

#+end_quote

Changing course if needed be is possible if we focus on small concrete tasks to work on, instead of big plans. We do what is needed at a time and work from there.
He does recommend having different manuscripts on different stages simultaneously (as long as we do not multitask). This is prevents us from getting *stuck or bored.*

This is another gold passage:
#+begin_quote
“When I am stuck for one moment, I leave it and do
something else.” When he was asked what else he did when he was stuck, his
answer was: “Well, writing other books. I always work on different
manuscripts at the same time. With this method, to work on different things
simultaneously, I never encounter any mental blockages.” (Luhmann,
Baecker, and Stanitzek 1987, 125–55)
#+end_quote


Write a draft *as a draft*. Dont be paranoid about the output. Also, proofread. Rigorously delete everything that has no function (kill your darlings).

*(main concepts)*

* Make it a habit

Obviously, doing all that is hard. We stick to our old bad habits. But we should
try to slowly change and remember that in the end we are not trying to
accumulate knowledge, but to become someone different with different ideas.

#+begin_quote
Learning, thinking and writing should not be about
accumulating knowledge, but about becoming a different person with a
different way of thinking.
#+end_quote
