#+TITLE: My Project Ideas
- tags :: [[file:20200628152829-my_weltanschauung.org][My Weltanschauung]]

Here are fleeting notes that ought to be better developed.

* On empiricism and conservatism


  One provocation that ought to be done is on empiricism. I believe that strict
  empiricism leads to an ontological conservatism a la Hegel "the real is
  rational".

** Further references

- wanderley guilherme dos santos
- ian shapiro
- john dunn
- charles mills
* Democratic advantage and ergodicity


  Many political theorists make dynamic arguments - about properties in time series. The insight is that the argument for democracy makes arguments about ensemble AND time averages. This is in robert dahl, mcgann even tocqueville. This should be formalized and connected with wanderley guilherme dos santos discussion about democratic transitions.

* Empirical dialectics and negativity


tenho um plano dormente de em contraponto a elster tentar make sense da epistemologia marxista.n uma defesa,mas atualizar e manter os insights (a la lawvere).obviamente precisaria expurgar o infalibilismo.quando se pensa uma dialetica falibilista o negativo ganha mais importancia


quando falo epistemologica tou pensando como o sistema "logico" vai levar a entender categorias e de quebra a pesquisa empirica
acho que o insight de marx na inversao dele em hegel é exatamente essa. dialetica pode ser invertida exatamente para nos ajudar a ver os buracos de conhecimento que enquanto em hegel sao resolvidos com mais abstracao em marx leva a investigacao da realidade concreta, mas ai ele tava imerso numa epoca em que a visao de conhecimento n era falibilista o bastante. acho que esse é o grande problema do sistema do ponto de vista cientifico

essa nocao de buracos acho tooopo

pq em prog mesmo vc deixa "buracos" no codigo e o sistema infere pra vc a partir de dicas. acho que tem um angu metodologico aqui

mas a partir o momento em que o falibilismo entre em cena a relacao entre categorias tem que ser mediada pela incerteza das proposicoes. intuitivamente isso leva a negatividade de adorno. enfim inutilidade da porra


no fim eu tenho a visao que da pra unificar a pratica cientifica por meio de uma triade de fontes: analiticos <-> pragmatistas <-> hegelianos materialistas ; como bom pos marxista acho que cada um é unilateral por um lado mas contribui por outro e que da pra unificar num sistema so

* From laws to algorithms
  From laws to principles to mechanisms to models to algorithms.

  My aim is to frame different ways of doing positive social theory. I'll show
  that those concepts suggest pretty different ways of representing and
  explaining the world.

  In this end this is part of a bigger project in algorithmic political theory.

  A good reference is:
- cite:Knuth1974art
- pearl works
- [[https://an1lam.github.io/post/2020-05-15-ci-course-review/][Stephen Malina - Course Review - Causal Inference]]
- The social software view
- the literature on modeling vs laws (weisberg, clarke and primo)

  
* Universalism and Social Choice


  To take balibar view of universalism as a site of conflict and connect with
  both social choice (universal domain) and the theory of majorities as
  coalitions of minorities. Any "universal" aggregation is leaving something
  out, and from a reflective point of view is open to criticism.

*  Social choice results as artifacts
- source :: cite:sep-voting-methods

  Pacuit makes the same question as I did years ago:
  #+begin_quote
  The main question is whether the voting paradoxes are simply features of the
  formal framework used to represent an election scenario or formalizations of
  real-life phenomena. This raises a number of subtle issues about the scope of
  mathematical modeling in the social sciences,
  #+end_quote

  This is directly related to the probability of any of the paradoxes
  (behavioral social choice) and to showing that they indeed occurred in an
  empirical setting (riker vs makie).

*  What are the 2 normative views of SCFs?
- source :: cite:sep-voting-methods

  One can justify and analyze social choice using a *procedural* (the right way)
  view or an *"epistemic"* (consequentialist).

  The most general article in the epistemic program is cite:Pivato_2012 .
  Conitzer also has some works on this approach (seeing SCFs as mles;
  cite:Conitzer_2013). This epistemic view is directly relevant to a project idea of using social choice to study ensembles.


* Social Choice and Central Authority




One implicit assumption in the Social Choice literature is that the work will be consumed by some sort of central authority, benevolent dictator. That is why cite:sep-voting-methods considers that the central question of social choice is the following:

#+begin_quote
Given a group of people faced with some decision, how should a central authority combine the individual opinions so as to best reflect the “overall group opinion”?
#+end_quote

This is a top down and statist perspective on group-decision making. One thing it ignores is the problem of choosing how to choose. That is something discussed by cite:Buchanan_1960 and its descendants. Group decision-making goes well beyond such liberal technocrat view and how to  incorporate social choice theory into such a bottom-up perspective.

For an almost anarchist approach to political economy see aligica and similars :
- cite:johnson19_remar_paul_dragos_aligic_public
- cite:allen18_crypt_its_instit_possib

* Sociotechnical view of formalization
  There is a widespread old-fashioned view of the virtues of formalization in
  the social sciences. The common argument is that formal models are useful
  because they are rigorous, and rigor leads to better argument. I disagree
  because this is an individualist, value-laden (rigorous good, mathematical
  good) and in the end misleading perspective on the role of formal models.

  This is obviously related to a more general empiricist perspective on
  modeling, but lets not dwell on that front.

  I have a sociotechnical view in the following way. Formal systems are a kind
  of language, with well delimited syntax and semantics. It is too restrictive
  to believe that there is a causal power behind this rigor. I can even draw a
  causal diagram that demonstrates that:

 #+BEGIN_LaTeX
  Rigor $\rightarrow$  Quality
 #+END_LaTeX

I believe however that a better perspective would emphasize?
- How we delegate cognition to the formal system, which has rules that take us
  beyond what, in the mean, is possible for a GOOD argument. Przeworski said
  something about that in an interview in Portuguese. This is a type of
  ARTIFICIAL intelligence.
- Another thing is that with the models we create symbolic artifacts which let
  us play with ideas and, more importantly, share them with other people (those
  who are trained in the syntax semantics of the formal system).
* Borda and intensity
  on cite:Laslier_2011 maurice salles argues that borda count somehow captures
  the intensity of voters preferences. This seems informal and should be further
  investigated.
* Can we connect the multiple district paradox with causal diagrams?

cite:sep-voting-methods says that the [[file:20200529174723-what_is_the_multiple_district_paradox.org][multiple district paradox]] is an instance
of simpson paradox. Pearl has famously discussed how to solve the simpson's
paradox through causal thinking. Can we then connect the literature of causal
diagrams with the literature on multiple district paradox?

** References
- For the connection with simpson paradox see : cite:Saari_2001
- For pearl discussion of simpson paradox see : cite:pearl2014comment
* Causal thinking and Social choice


  This is a general idea about connecting the two areas. There is some work
  connecting Shapley values with causal thinking (LOOK FOR REFERENCES). This
  connection of collective decision making is hinted at hamburgs page. [[https://www.wiso.uni-hamburg.de/en/forschung/verbundprojekte/rtg-collective-decision-making/research/p6.html][P6:
  Causality and responsibility in collective decision-making : DFG Graduate...]]

 Beyond the references in this page Kai spiekerman, according to
  cite:sep-social-choice, also has papers using bayesian networks to model
  judgement aggregation. Only one more step is needed to make the connection !!!
  ALSO there is some work by Brendan Fong modeling bayesian networks using
  category theory. Maybe there is even another venue of research here.




** Copy of hamburgs page
P6: Causality and responsibility in collective decision-making

Attributions of responsibility are a very elementary means by which we regulate our social, political, and economic affairs. As a matter of fairness and efficiency it is quite obvious that we need to get the “responsibility system” right. There are two approaches to understanding and designing a responsibility system. The first is abstract: it starts from general concepts and principles including prerequisites for responsibility in terms of causation (we call this theoretical responsibility). The second is behavioral: it starts from purposive agents in whom morality is one of many determinants of behavior.

This research project will examine responsibility from these two perspectives, thus naturally combining and integrating philosophical and economic methodologies, along with reflections on responsibility.
Objectives

    To develop a unified framework for causal contributions in collective decision-making.
    To explore metrics of moral responsibility for collective decision-making.
    To investigate the effect of technology on the distribution of responsibility.

Supervisors
Suggested Readings

Barberà, S. and A. Gerber (2017): “Sequential Voting and Agenda Manipulation,” Theoretical Economics, 12, 211-247.

Braham, M. and M. van Hees (2012): “An Anatomy of Responsibility,” Mind, 121, 601-634.

Dehez, P. and S. Ferey (2013): “How to share joint liability: A cooperative game approach,” Mathematical Social Sciences, 66, 44-50

Duch, R., Przepiorka, W. and R. Stevenson (2015): “Responsibility Attribution for Collective Decision Makers”, American Journal of Political Science, 59, 372-389.

Floridi, L. (2013): “Distributed morality in an information society,” Science and Engineering Ethics, 19, 727-743.

Halpern, J. (2016): Actual Causality, Cambridge, Mass.: MIT Press.

Kroedel, T. (2015): “A Simple Argument for Downward Causation,” Synthese, 192, 841-858.

List, C. and P. Pettit (2011): Group Agency: The Possibility, Design, and Status of Corporate Agents, Oxford: Oxford University Press.

Moore, M. (2009): Causation and Responsibility: An Essay in Law, Morals, and Metaphysics, Oxford:Oxford University Press.

Rothenhäusler, D., Schweizer, N. and N. Szech (2018): “Guilt in voting and public good games,” European Economic Review, 101, 664-681.

* Generalizing Ranking and Approving


  cite:sep-voting-methods says the following :

  #+begin_quote
They are asked to determine which candidates they approve of rather than selecting a single candidate to voter for or determining the relative ranking of the candidates. That is, the voters are asked which candidates are above a certain “threshold of acceptance”. Ranking a set of candidates and selecting the candidates that are approved are two different aspects of a voters overall opinion about the candidates. *They are related but cannot be derived from each other.*
  #+end_quote

  How can we formalize this insight that ranking and approving are related but cannot be derived from each other. In what sense are they related? What is the concept that connects them ?

** useful refs

Brams, S. and Sanver, M. R., “Voting systems that combine approval and
preference,” in The Mathematics of Preference, Choice, and Order: Essays in
Honor of Peter C. Fishburn, S. Brams, W. Gehrlein, and F. Roberts (eds.), pp.
215–237, Berlin: Springer.
* Bolsonaro and condorcet consistent voting
- tags ::  [[file:20200531170641-is_plurality_rule_justified.org][Is plurality rule justifiable?]]

not condorcet winnner, not even borda winner, worst from a dynamical point of view.

** Further references

*** Political Theoretical references
- shklar stuff
- berlin has something to say here too
- as well as shapiro
- przeworski

*** Political economy references
- cite:mcclintock18_reeval_runof_latin_americ
- for-links-mcclintock_lasa_2019.pdf in pdfs folder (add the reference later)
- cite:tabarrok1999would
- cite:tabarrok2001president

* On the conditions of manipulability of voting methods



One insight that i got reading cite:Laslier_2011 is the following argument :

  #+begin_quote
Arguments about the relatively large probability with which some of these voting
rules can be manipulated are typically based on the assumption that one group of
voters with similar preferences can manipulate the outcome, while all other
voters are completely naive to the situation.
  #+end_quote

  Maybe this can be connected with binmore argument about the applicability of rational choice. High stake situations. DEVELOP IT MORE.

Manipulability may be something more of theoretical interest, *what are the odds?*  maybe this depends on the context. *Maybe I can connect with the idea of condition of applicability of the rational choice model (from binmore)*. Binmore considers that high stake situations are the ones that are closer to the rational actor. I can look at my dissertation to think about that, but committees are much closer to the rational choice applicability and as such amenable to manipulation. Gotta think how manipulability might happen in large scale elections and whether this happens. Large elections don't seem to be such a case.

This scale difference can be connected with computation and physics through the transition lit. This is a cool idea that can be developed throughout the cite:moore2011nature course!!
* Axiomatic Analysis of Indices


  Following cite:patty2015aggregation try to give a formal analysis of lets say
  democracy indices. One example could be cite:L_HRMANN_2020 or
  cite:mariani20_networ_based_rankin_social_system . Actually,
  cite:mariani20_networ_based_rankin_social_system can be connected with Patty
  and Penn other work on characterization of networks (cite:Patty_2014).
  Furthermore, I could be recursive and use social choice to understand
  ideological scaling methods. What are we doing from an aggregative point of
  view when we collapse answers in surveys into a single scale?


cite:patty2015aggregation make the following points regarding indices which fit
neatly on this idea. First they define indices:
#+begin_quote
An index in our terminology is an aggregation method that assigns each
alternative a numeric score on each of the ­criteria and—more
importantly—presumes that these scores are comparable across criteria.
#+end_quote
Consequently they propose that indices are related to some latent dimension.
This is something that is hand-wavy and should be further refined. The quote is
the following:

#+begin_quote
in nearly every situation, an index is at best an i ­ mperfect measure of some
latent (i.e., imperfectly observed) trait or quality of the alternatives under
­consideration.
#+end_quote


* Majority tiranny, deliberation and voting


This mind changing hypothesis should be investigated (cite:Laslier_2011):

#+begin_quote
I view voting as a useful mechanism for making collective decisions when
unanimous agreement is not possible. Elections should generally be preceded by
discussions about the candidates and the importance that the voters attach to
the election. If a minority of voters feels strongly about some candidates while
the other voters are almost indifferent between these candidates, then it should
be possible for the minority to convince sufficiently many of the others to
change their minds prior to the vote-casting process. (I believe that in cases
of near-indifference, most people’s desire to preserve social harmony trumps
rent-seeking.) If it is not possible to change sufficiently many voters’ minds,
then I would interpret this as evidence that the intensity in preferences
between the groups is not as disparate as it might appear. I therefore feel
comfortable ignoring voting rules that take account of the intensities of
voters’ preferences.




#+end_quote

* Approval is about support or tolerance? Does this matter?

Nurmi argues the following in cite:Laslier_2011:

#+begin_quote
Does the fact that I approve of a candidate mean that I can tolerate him as the
mayor without resorting to active resistance or does it mean that I positively
support him/her? I think this is what makes the approval voting results hard to
interpret, but I guess a mayor that is even tolerated by more voters than any
other candidate has at least tolerable prospects.
#+end_quote
