#+TITLE: On types of notes
- tags :: [[file:20200525200536-on_my_workflow.org][On my workflow]]


There are at least five kinds of notes:
1. Fleeting notes
2. Literature notes
3. Reference notes
4. Permanent notes
5. Higher level permanent notes

** Fleeting notes

Those are informal notes on any thought or idea that pops into my mind.
I may write them using org-journal or an actual diary.

** Literature notes
Those are to write about concepts and ideas that I've studied from a variety of
sources, such as papers, books, sites, videos. They should be kept small/atomic,
particularly their outlines. If they grow big they might be better off as
reference or permanent notes. They should be written in my own words and I must
write the bibliographic source.

They will be create from source notes.

** Reference notes

Those are split from literature notes when they are mentioned by more than one
source. They should be written with my own words and as if I'm writing for
someone else.


** Permanent notes
Those are written after reviewing fleeting notes and literature notes. They
should be written as if addressed to someone else, that is, with backing, full
sentences, sentences and so on.

One should try to answer the following questions:

- What is it about ?
- What does it mean for ...?
- How does the new information contradict, correct, support, or add to what I already know?
- How can I combine ideas to generate something new?
- What questions are triggered by these new ideas?

Those will be written using org-roam

** Higher level notes
This is my own classification, the sources I've seen consider them special
permanent. Nevertheless, I seen them as reflections *not upon sources, but upon
the own notes.* The are two kinds of them outline notes and connection notes.
Connection notes are about linking notes together and indexing them. We could
also call them indexes notes. Outline notes, on the other hand, are those in
which we create an argument or story with the notes.

They can also be written using org-roam.
