#+TITLE: On types of notes
#+OPTIONS: toc:nil
#+OPTIONS: date:nil
- tags :: [[file:20200525200536-on_my_workflow.org][On my workflow]]

There are at least four kinds of notes:
1. Fleeting notes
2. Literature notes
3. Permanent notes
4. Higher level permanent notes.

** Fleeting notes

Those are informal notes on any thought or idea that pops into my mind.

They go into an idea inbox or simply a note which collects them. They should be processed daily into permanent notes, lest we create a thoughts graveyard. 

** Literature notes

Those are to write about concepts and ideas that I've studied from a variety of
sources, such as papers, books, sites, videos. They should be kept small/atomic,
particularly their outlines (defined below). If they grow, big they might be
better off split into permanent notes. They should be written in my own words
and I must write the bibliographic source.


** Permanent notes
Those are written after reviewing fleeting notes and literature notes. They
should be written as if addressed to someone else, that is, with backing, full
sentences, sentences and so on.

One should try to answer the following questions:

- What is it about ?
- What does it mean for ...?
- How does the new information contradict, correct, support, or add to what I already know?
- How can I combine ideas to generate something new?
- What questions are triggered by these new ideas?

They should not be too big. 

** Higher level notes
This is my own classification, the sources I've seen consider them special
permanent. Nevertheless, I've seen them as reflections *not upon sources, but upon
the own notes.*

There are, at least, three kinds of higher level notes:
- index
- outline
- desktop

There is a single index note. It lists entry points to typical clusters in my slip-box. I should not focus too much on the index, as with roam you can *see* them.

The entry points in the index note are the outline notes. Those give a provisional structure of a topic. It structures and introduces other related notes.


There are two kinds of them outline notes and desktop notes.
Connection notes are about linking notes together and indexing them. We could
also call them indexes notes. Outline notes, on the other hand, are those in
which we create an argument or story with the notes.

They can also be written using org-roam.
