#+title: The tradegy of democratic centralism: war and democratic decoupling

Democratic Centralism is an organizational theory which was created in a context
of revolutionary activity. As such, it was successful in Russia and widely
disseminated. From a social choice theoretic perspective it is interesting to
analyze it, since it an "oligarchic" solution to the paradoxes that might emerge
from collective decision processes. That is, from an evolutionary perspective in
which the environment is war-like it might be a fit form. However, the
democratic processes imposes a different set of fitness requirements. Though
highly disseminated, the organizational form might under-perform in the
democratic competition, inasmuch its centralized committee structure can lead to
a top committee which is unable to adapt to the demands of the electorate, since
it is based upon a vanguardist vision of the Party, in an environment of
constantly shifting coalitions and majorities. The Worker's party in Brazil is a
case in point, and the strategic mistake of the last elections instantiates how
harmful that can be for the party.

* Further references
- Elster gotta have something to say about that
- Przeworski article! [[https://phenomenalworld.org/analysis/revolution-reform-resignation][Phenomenal World | Revolution, Reform, and Resignation]]
- cite:bolleyer2013new
- cite:feld2014modeling
- cite:kaminski06_gener_equil_model_multi_party_compet
