#+TITLE: Perspectives on the comparative study of electoral systems
#+ROAM_KEY: cite:grofman16_persp_compar_study_elect_system
* TODO Notes
:PROPERTIES:
:Custom_ID: grofman16_persp_compar_study_elect_system
:NOTER_DOCUMENT: /home/mvmaciel/Drive/Org/pdfs/grofman16_persp_compar_study_elect_system.pdf
:AUTHOR: Grofman, B.
:JOURNAL: Annual Review of Political Science
:DATE:
:YEAR: 2016
:DOI:  http://dx.doi.org/10.1146/annurev-polisci-020614-092344
:URL: https://doi.org/10.1146/annurev-polisci-020614-092344
:END:




* Why am I reading this/ Where this might be useful/Which project or idea that I already have will benefit from this and how?
This is directly related to my [[file:20200711104510-bolsonaro_and_condorcet_consystency.org][Bolsonaro and condorcet consystency]] thingy.
Also, to talk with Grofman. NERVOUS.

* Struct questions

** What is the goal/ general argument of the text?
The use of knowledge about electoral systems for electoral engineering is typically related to 5 problems:
#+begin_quote
How do electoral systems affect (a) the proportionality of seats–
votes relationships, (b) party proliferation, (c) the ideological nature of party
competition, (d ) voter turnout, and (e) the degree of match between the
preferences of citizens and the policy choices of the government?
#+end_quote
** What are the specific arguments of the text?

** What are the main concepts of the text?
