#+TITLE: cite:Explanation 
#+ROAM_KEY: cite:roth2010explanation
* TODO Notes
:PROPERTIES:
:Custom_ID: roth2010explanation
:NOTER_DOCUMENT: %(orb-process-file-field "roth2010explanation")
:AUTHOR: Roth, P. A.
:JOURNAL:
:DATE:
:YEAR: 2010
:DOI:
:URL:
:END:



* Why am I reading this/ Where this might be useful/Which project or idea that I already have will benefit from this and how?
I am reading this text to understand what counts as an explanation and how it relates to causality and interpretation. Particularly, I intend to use cite:johnson2006consequences, cite:king1994designing, cite:roberts18_what_is_polit_method,
cite:slembrouck01_explan_inter_critiq_analy_discour

and delineate what is what. Right now, I believe that the interventionist view gives the proper conceptualization of causality, but not of explanation. The cause of effects vs effects of causes debate by cite:morton2010experimental and the arguments of cite:johnson2006consequences and Goldthorpe about causal mechanisms allow me to argue that causality is something akin to RCM, but causal mechanisms are needed for proper explanation.
* Struct questions

** What is the goal/ general argument of the text?
To define what explanation is, or at least to say how it has been traditionally defined. 
** What are the specific arguments of the text?

** What are the main concepts of the text?
- explanation vs interpretation : reconstruct agents reasons for actions vs robust predictive value
  #+begin_quote
The most fundamental concerns whether
or not the goal or purpose of social inquiry should
be to reconstruct actions (i.e., purposive behavior)
in terms of an agent’s (individual actor’s) perspec-
tive. An alternative view maintains that the pur-
pose of social inquiry should be to develop
explanations, that is, accounts that have robust
predictive value.
  #+end_quote
- positivist
  #+begin_quote
, the term positivism enjoys wide use
as an epithet attached to all views that insist that
the purpose of social science explanation requires
being able to apply generalizations to account for
observed cases
  #+end_quote
