#+TITLE: Mathematics: a discrete introduction
#+ROAM_KEY: cite:scheinerman2012mathematics
*  Notes
:PROPERTIES:
:Custom_ID: scheinerman2012mathematics
:NOTER_DOCUMENT: %(orb-process-file-field "scheinerman2012mathematics")
:AUTHOR: Scheinerman, E. A.
:JOURNAL:
:DATE:
:YEAR: 2012
:DOI:
:URL:
:END:


* Why am I reading this/ Where this might be useful/Which project or idea that I already have will benefit from this and how?
It will help me with algorithms and anything related to social computational trinitarianism.
Related readings are cite:moore2011nature and cite:Hall_2000 .



* Struct questions

** What is the general argument of the text?
** What are the specific arguments of the text?
** What are the main concepts of the text?
- *Composto* : Um numero positivo \(a\) é composto se existe um inteiro \(b\) t.q. \(1 < b< a\) e  \(b |a\) .
- *Perfeito*: Um numero inteiro \(n\) é perfeito se for igual a soma de seus divisores positivos inferiores a
-
*** Chap 2
- *Fatorial imcompleto*: \((n)_k = n(n-1)(n-2)\ldots[(n-(k-1)] = n(n-1)(n-2)\ldots(n-k+1)\)
- *Fatorial* é um caso especial em que \(k=n\).
- How does one prove that the cardinality of a power set of \(A\) is \(2^{|A|\) ? By showing that this is equivalent to a include-exclude decision tree.
- Cardinality clusion exclusion \(|A \cup B| = |A| + |B| - |A \cap B|\)

*** Chap 3
- Notice that reflexivity is about the whole A, while symmetry and transitivity are conditional on being on R. This is what explains a relation being reflexive and transitive but not symmetric, there may be elements of A which are not in R.
  - Example: \(A=\{1,2,3\}\) and \(R = \{(1,2), (2,1), (1,1), (2,2)\}\)
- An *Equivalence relation* is one that is:
  - Reflexive
  - Symmetric
  - Transitive
  - But NOT anti-reflexive and not anti-symmetric
- Two numbers (\(x,y\)) are *congruent modulo n* if \(n|(x-y)\). We use the following notation to say that: \(x \equiv y \pmod{n}\)
- Let \(R\) be an equivalence relation on \(A\) and \(a \in A\) . An *Equivalence class* of \(a\) is the set of all element of \(A\) related, by \(R\), to \(a\). That is:
  Then, to define an equivalence class we need of:
  - \(R \subseteq A \times A\) which is an equivalence relation (symmetric, transitive and reflexive)
  - An \(a \in A\) ;
  - and the set \([a] =\{x \in A : xRa\}\), the so called equivalence class
- An important theorem: the congruence mod n is an equivalence relation on the set of integers. As such it will define equivalence classes.
  - From the programming perspective the mod equilavence class is defined through a partial function isnt it?
- A few important theorems about equivalence classes:
  1. Let \(R\) is an equivalence class on \(A\) and \(a \in A\) . Then \(a \in [a]\)
  2. Let \(R\) is an equivalence class on \(A\) and \(a,b \in A\). Then \(aRb \iff [a] = [b]\).
  3. Let \(R\) is an equivalence class on \(A\) and \(a,x,y \in A\). If \(x,y \in [a]\) then \(xRy\).
-

* Exercises
** CHap 1
*** 5
- 5.1
  - Let x and y be odd. Then there is an \(a\) s.t.  \(x = 2a + 1\) and a \(b\) s.t. \(y = 2b + 1 \). Then \(x + 1 = 2a+1 + 2b +1 = 2a+2b+2 = 2(a+b+1)\). Since a+b+1 is an integer it follows that \(x+y\) is even.
- 5.2
  - Let x  be odd and y be even. Then there is an \(a\) s.t.  \(x = 2a + 1\) and a \(b\) s.t. \(y = 2b\). Then \(x+1 = 2a + 1 + 2b = 2(a+b) + 1\). Since a and b are integers their sum is also an integer. Then, \(x+y\)  is odd.
- 5.3
  - Let \(n\) be odd. Then there is an \(a\) s.t. \(n = 2a + 1\) Then \(-n = -2a - 1 = -2a - 2 + 1  = 2(-a-1) + 1\) . Hence, \(-n\)  is odd.
- 5.4
  - Let x and y be even. Then there is an \(a\) s.t.  \(x = 2a\) and a \(b\) s.t. \(y = 2b \). Then \(xy = 2a2b = 2(2ab)\) . Hence, \(xy\) is even - since it is divisible by 2.
- 5.5
  - Let x be odd and y be even. Then there is an \(a\) s.t.  \(x = 2a + 1\) and a \(b\) s.t. \(y = 2b\). Then \(xy = (2a + 1)(2b) = 2(2ab + b)\). Since it is divisible by 2, \(xy\) is even.
- 5.6
  + Let x and y be odd. Then there is an \(a\) s.t. \(x = 2a + 1\) and a \(b\)
    s.t. \(y = 2b + 1 \). Then \(xy = (2a+1) (2b + 1 ) = 2a2b + 2a + 2b + 1 =
    2(ab + a + b) + 1 \). let \(k = (ab + a + b) \) then k is an integer. Since \(xy = 2k+1\) it follows that it is odd.
- 5.7
  - Let \(n\) be odd. Then there is an \(a\) s.t. \(n = 2a + 1\). Then \(n^2 =
    (2a + 1)(2a+1) = (2a2a+2a+2a+1)= 2(2a^2+a)+1\). Hence, \(n^2\) is odd.

- 5.9
  + Suppose \(a|b\) and \(a|c\). Then there is a \(az = b\) and a \(aw = c\). then \(b+c = az + aw = a(z+w)\). Since \(z+w\) is also an integer it follows that \(a|(b+c)\).
- 5.11
  - Let \(a,b,d,x,y \in \mathbb{Z}\) . Suppose \(d|a\) and \(d|b\) . Then there  is \(dk =a\) and a \(dw = b\). Then \(ax = dkx\),  \(by = dwy\) and \(ax + by = dkx + dwy = d(kx + wy)\). Since \( (kx +wy) \in \mathbb{Z}\) then \(d|(ax +by)\) .

- 5.12
  - Suppose \(a|b\) and \(c|d\) . Then there is a \(aw=b\) and a \(ck =d\). Then \(bd = awck = (ac)(wk)\). Hence \((ac)|(bd)\).

- 5.13
  - x is odd iff there is an \(a\) s.t. x = 2a + 1 iff x+1 = 2a +2 = 2(a+1) iff x+1 is even.
- 5.14
  - x is odd iff there is an \(a\) s.t. x = 2a + 1 = 2b - 2 + 1 = 2b - 1,  where  a = b - 1. (a proper proof would be two sided).

- 5.15
  - Suppose \(0|x\), then there is an \(a * 0 = x\), but we know that 0
    multiplied by anything is equal to 0, so \(x=0\). Now suppose \(x = 0\). Then x multiplied by any \(a\) will be equal to 0:  \(ax = a * 0\). Then \(0|x\).
**** TODO 5.17 onwards
- 5.17
  - Goal: \(\sqrt{a} < {a \over x} < a\)
  - Suppose \(a>1\) and \(1 < \sqrt{a} < a\) .
  - Now suppose \(1<x<\sqrt{a}\) . Then \({1 \over x} < 1 < {a \over x }\)  and \(a < a\sqrt{a} < a^2\) \(1 < \sqrt{a} < a\)\(1 < \sqrt{a} < a\)\(1 < \sqrt{a} < a\)\(1 < \sqrt{a} < a\)
*** Self-test
-
** Chap 2
*** 8
- 8.1
  - 20
- 8.2
  - 26^3
- 8.3
  - 2^k ?
- 8.4
  - (* 4 2 2 4 ) = 64
- 8.5
  - \((500 \times 499 \times \ldots 481) \times 2\)
  - \(500 \times 499 \times \ldots 461\)
** Chap 3
- 14.7
  - c: \(y = x + 1\)
  - d: \(y|x\)
  - e: \(yx < 0\)
- 14.9
  - \(\leq\) is a counterexample. It is antisymmetric but is not antireflexive
- 14.16
  - Always remember that R is not equal to A. The affirmation about transitive and symmetry supose x,y,z in R to imply something about those elements. This means that a set might be symmetric and transitive but not reflexive. This is because reflexivity is an universal property of A, while symmetry and transitivity are conditional on something being on R. More concretely, let \(A=\{1,2,3\}\) and \(R = \{(1,2), (2,1), (1,1), (2,2)\}\). Notice that \(R\) is symmetric and transitive, but not reflexive.

- 15.1
  - a: n = 2 or n = 5 or n = 10
  - b: n = 5
  - c: n = 2 or 3 or 9 or 37 or 54
  - d: there is no such n
- 15.2
  - a-b
- 15.3
  a. T
  b. F
  c. F
  d. F
  e. T
  f. F
  g. ?
- 15.4
  Suppose they are even. Then there is an \(a\) and a \(b\) s.t. \(2a = x \) and \(2b = y\). Then \(x-y = 2(a-b)\) . This implies \(2 | (x-y)\) , thus \(x \equiv y \pmod{2} \) . Now suppose they are odd. Then there is an Then there is an \(a\) and a \(b\) s.t. \(2a  + 1 = x \) and \(2b + 1 = y\). Then \(x-y = 2 a + 1 - (2b+1) = 2(a-b)\). This implies once again \(2 | (x-y)\) and \(x \equiv y \pmod{2}\) .

- 15.5. Too easy: \(a-(-a) = 2a\) Thus \(2|(a - (-a))\) which means that \(a \equiv -a \pmod{2}\).
- 15.6
  - Let \(\equiv \; =   \pmod{n} \). Now \(x \equiv y\) and \(y \equiv z\) is equivalent to saying that \(n|(y-z)\) and that \(n|(x-y)\). From exercise 5.9 from chap 1 we know that \(n|[(x-y) + (y-z)]\) =  \(n|(x-z)\), that is the same as \(x \equiv z \).
    - Without using 5.9 we could say that there is an a and a b s.t \(nb = y-z\) and \(na= x-y\). Then \(nb+na = n(b+a) = y-z + x -y = x-z\). From \(n(a+b) = x-z\) we derive that \(n|(x-z)\), since \(a,b\) are integers. Thus, \(x \equiv z \).

- 15.12
  - Suppose \(x,y \in [a]\). Then \(xRa\) and \(yRa\). By symmetry it follows that \(aRy\). \(xRa\) and \(aRy\), by transitivity, leads to \(xRy\). Thus, if \(x,y \in [a]\) then \(xRy\).
