#+title: url:Understanding Society: Reduction and generativeness
#+roam_key: https://understandingsociety.blogspot.com/2016/03/reduction-and-generativeness.html
- tags :: [[file:understanding_society_abm_fundamentalism.org][url:Understanding Society: ABM fundamentalism]]

An ontology of complex entities naturally leads to the notion of levels.What are
the possible relationships between levels?
    #+begin_quote
  - Facts about things and properties of B are generated by facts of A
  - Facts about things and properties of B can be reduced to facts of A
  - Facts about things and properties of B supervene upon properties of A
  - Facts about things and properties of B are weakly emergent from properties of A
  - Facts about things and properties of B are strongly emergent from properties of A
  - Facts about things and properties of B are in part independent from the properties of A
  - Facts about things and properties of B causally influence the properties of A
  #+end_quote
    Even if we accept that a level is generated by the other it does not mean
    that the higher level can be reduced, in the computational sense, to the
    lower. It does not mean that our *knowledge* of the higher level has to make
    use of all our knowledge of the lower or that to understand the higher level
    we have to always derive it from the lower. It may be, for example,
    computationally impossible. We might not have all that lower level data.
    Finally it might be *less effective* to do so.

    #+begin_quote
*Generativity is not a feature of theories*; instead, it is an ontological feature
of the world. [...] But *there is no assurance that our current knowledge about B
permits a mathematical derivation of A*. [...] And then there is the issue of
computability: *it may be radically infeasible to perform the calculations
necessary to derive A from B*. And so it is clear that reducibility does not
follow from generativeness. [...] So *it is fully consistent for us to take the position of generativeness and anti-reductionism.* [...]
We can take the view
that all social entities are embodied in facts about various individuals, their
social interactions, and their states of mind. This implies that social facts
are generated by facts at the actor level[...] And yet we can also be emphatic
in affirming that there is not need or general possibility for reduction from
the one level to the other.
    #+end_quote






s


















*Generativity is not a feature of theories*; instead, it is an ontological feature
of the world. [...] But *there is no assurance that our current knowledge about B
permits a mathematical derivation of A*. [...] And then there is the issue of
computability: *it may be radically infeasible to perform the calculations
necessary to derive A from B*. And so it is clear that reducibility does not
follow from generativeness. [...] So *it is fully consistent for us to take the position of generativeness and anti-reductionism.* [...]
We can take the view
that all social entities are embodied in facts about various individuals, their
social interactions, and their states of mind. This implies that social facts
are generated by facts at the actor level[...] And yet we can also be emphatic
in affirming that there is not need or general possibility for reduction from
the one level to the other.
